### ISSUE TITLE
Sarah Introduction

### ISSUE THREAD

**Issue by sarahmasri** [stat545ubc-2023/collaborative-group12#1]
## Milestone 1 Exercise 4: Introduction
Hello everyone. My name is Sarah Masri. I am a first year Masters student in the department of Statistics. I did my undergraduate degree at UBC in Math and Stats with some research in lineage tracing. 

@jmfvieira11 @hotz1 @poppypeapea

**Comment by jmfvieira11** [comment]
Hello Sarah! Nice to meet you! =D

**Comment by hotz1** [comment]
Hi Sarah! Thanks for tagging me in this. I'll be sure to work on this issue right away.

**Comment by poppypeapea** [comment]
Hi Sarah. Nice tou meet you.

**Comment by poppypeapea** [comment]
Hi Sarah. Nice to meet you.
