### ISSUE TITLE
Xiangwen Introduction

### ISSUE THREAD

**Issue by poppypeapea** [stat545ubc-2023/collaborative-group12#2]
## MileStone1 Exercise 4
Hello, everyone! My name is Xiangwen Li, and I am a first-year master's student in Electrical and Computer Engineering.

@hotz1 @jmfvieira11 @sarahmasri

**Comment by sarahmasri** [comment]
Hi Xiangwen! Nice to meet you!!

**Comment by hotz1** [comment]
Hi Xiangwen! Thanks for the introduction. It's very nice to meet you!

**Comment by jmfvieira11** [comment]
Hello Xiangwen Li! Nice to meet you =^w^=
