### ISSUE TITLE
Juliana's Introduction

### ISSUE THREAD

**Issue by jmfvieira11** [stat545ubc-2023/collaborative-group12#3]
## Milestone 1

Greetings, I'm Juliana, a coffee enthusiast ☕ with a molecular biology background 🔬 Currently, I'm on a quest to conquer a master's degree to unravel the mysteries of life, one caffeinated molecule at a time! 🧬📚

@hotz1 @poppypeapea @sarahmasri

**Comment by poppypeapea** [comment]
Hi Juliana, nice to meet you.

**Comment by sarahmasri** [comment]
Hi Juliana! I also love coffee. My favourite coffee shop on campus is Bean Around the World. I look forward to hearing about your research!

**Comment by hotz1** [comment]
Hi Juliana, have you uncovered any mysteries so far that I should know about?

Thanks,
Joey
