### ISSUE TITLE
Joey's Introduction

### ISSUE THREAD

**Issue by hotz1** [stat545ubc-2023/collaborative-group12#4]
# Joey's Introduction

Hi everyone! My name is Joey, and I am a first-year Masters student in the Department of Statistics. I am originally from Toronto, and I did my undergrad degree in Data Science and Statistics at the University of Toronto.

These are my other three team members:
1. @jmfvieira11
2. @sarahmasri
3. @poppypeapea

**Comment by poppypeapea** [comment]
Hi Joey. Nice to meet you.

**Comment by sarahmasri** [comment]
Hi Joey! I didn't know that U of T had a major in Data Science, very cool!

**Comment by jmfvieira11** [comment]
Hi Joey! Nice to meet you!! :)
